Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -11,8 +11,8 @@ pool:
 
 variables:
   GOBIN:  '$(GOPATH)/bin' # Go binaries path
-  GOROOT: '/usr/local/go1.11' # Go installation path
-  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
+  GOROOT: '$(Agent.BuildDirectory)/go' # Go installation path
+  GOPATH: '$(Agent.BuildDirectory)/gopath' # Go workspace path
   modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
 
 steps:
@@ -25,15 +25,43 @@ steps:
     mv !(gopath) '$(modulePath)'
     echo '##vso[task.prependpath]$(GOBIN)'
     echo '##vso[task.prependpath]$(GOROOT)/bin'
+    wget "https://storage.googleapis.com/golang/go1.12.3.linux-amd64.tar.gz" --output-document "$(Agent.BuildDirectory)/go1.12.3.tar.gz"
+    tar -C '$(Agent.BuildDirectory)' -xzf "$(Agent.BuildDirectory)/go1.12.3.tar.gz"
   displayName: 'Set up the Go workspace'
 
 - script: |
-    go version
-    go get -v -t -d ./...
-    if [ -f Gopkg.toml ]; then
-        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
-        dep ensure
+    go get github.com/mitchellh/gox
+
+    mkdir -p release
+
+    read -rp "Cleaning $PWD/release directory. Proceed? [y/n]" res
+    if [ ! "$res" == "y" ]; then
+      echo "Abort"
+      exit 1
     fi
-    go build -v .
+
+    rm -rf ./release/*
+
+
+    v="$(git describe --tags)"
+
+    output="{{.Dir}}-{{.OS}}-{{.Arch}}-$v"
+    osarch="!darwin/arm !darwin/arm64 !darwin/386"
+
+    echo "Compiling:"
+
+    os="windows linux darwin"
+    arch="amd64 386 arm arm64 mips mips64 mipsle mips64le"
+    pushd cmd/ck-client || exit 1
+    gox -ldflags "-X main.version=${v}" -os="$os" -arch="$arch" -osarch="$osarch" -output="$output"
+    GOOS="linux" GOARCH="mips" GOMIPS="softfloat" go build -ldflags "-X main.version=${v}" -o ck-client-linux-mips_softfloat-"${v}"
+    GOOS="linux" GOARCH="mipsle" GOMIPS="softfloat" go build -ldflags "-X main.version=${v}" -o ck-client-linux-mipsle_softfloat-"${v}"
+    mv ck-client-* ../../release
+
+    os="linux"
+    arch="amd64 386 arm arm64"
+    pushd ../ck-server || exit 1
+    gox -ldflags "-X main.version=${v}" -os="$os" -arch="$arch" -osarch="$osarch" -output="$output"
+    mv ck-server-* ../../release  
   workingDirectory: '$(modulePath)'
   displayName: 'Get dependencies, then build'
